version: 2

build:
  os: "windows-latest"
  tools:
    python: "3.10"

# Build from the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Explicitly set the version of Python and its requirements
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .